"""Add indexes and update models

Revision ID: 644cc8ff852c
Revises: 470338af745d
Create Date: 2026-07-20 13:48:49.042675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '644cc8ff852c'
down_revision: Union[str, Sequence[str], None] = '470338af745d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'error_message',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'error_message',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
